# -*- coding: utf-8 -*-
"""Fake and Real News Detection_RNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1onF5lEFGbB4559eqY0VbJNpUGAwBSOvg

<table align="center" width=100%>
    <tr>
        <td width="10%">
            <img src="">
        </td>
        <td>
            <div align="center">
                <font color="#21618C" size=24px>
                    <b>Fake and Real News Detection
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

## Problem Statement

The problem of fake and real news detection is to develop an automated system that can distinguish between genuine news articles and fake news articles. With the rise of social media and the internet, fake news has become a significant issue that can have far-reaching consequences. Fake news can cause confusion, influence public opinion, and even have political implications.

The problem of fake and real news detection involves building a model that can automatically identify features that distinguish genuine news articles from fake ones. The model is trained on a dataset of labeled news articles, where each article is labeled as either real or fake. The model is then tested on a separate set of articles to evaluate its accuracy.

## Icon Legends
<table>
  <tr>
    <th width="25%"> <img src="infer.png" style="width:25%;"></th>
    <th width="25%"> <img src="alsoreadicon.png" style="width:25%;"></th>
    <th width="25%"> <img src="todo.png" style="width:25%;"></th>
    <th width="25%"> <img src="quicktip.png" style="width:25%;"></th>
  </tr>
  <tr>
    <td><div align="center" style="font-size:120%">
        <font color="#21618C"><b>Inferences from Outcome</b></font></div>
    </td>
    <td><div align="center" style="font-size:120%">
        <font color="#21618C"><b>Additional Reads</b></font></div>
    </td>
    <td><div align="center" style="font-size:120%">
        <font color="#21618C"><b>Lets do it</b></font></div>
    </td>
    <td><div align="center" style="font-size:120%">
        <font color="#21618C"><b>Quick Tips</b></font></div>
    </td>

</tr>

</table>

## Table of Contents

1. **[Import Libraries](#import_lib)**
2. **[Visualizing text and ploting word cloud](#visualize_ids)**
3. **[Data Analysis](#data_analysis)**

    - 3.1 - Cleaning Data
    - 3.2 - Bag of Words
    - 3.3 - MultinomialNB Algorithm
    - 3.4 - TF-IDF
	- 3.5 - word vectorization
	- 3.6 -	word2 vec
    - 3.7 - Stemming
    - 3.8 - Tokenization

### **Importing Libraries**
"""

# # To mont the google drive

# from google.colab import drive
# drive.mount('/content/drive')

# Importing the libraries

import numpy as np             # numpy is a numerical python used to work with array
import pandas as pd            # pandas is used for data manipulation
import matplotlib.pyplot as plt       # matplotlib used for visualization
import seaborn as sns                 # seaborn is used for visualization purpose built top of matplotlib
import nltk            # Natural Language Tool Kit used to process the data in human spoken language (it allows us to apply different kind of technique such as parsing,tokenization,lemmatization,stemming etc)
import re                   # regular expression for string manipulations
from wordcloud import WordCloud       # Text visualization python package

from tensorflow.keras.preprocessing.text import Tokenizer  # tokenization is used to split a paragraph or entire text in to smaller units, this smaller units are called as tokens, it is used to get the individual words (it is used to count the number of words in a sentence and it helps to interpret the meaning of the text by analyzing the word present in a text)
from tensorflow.keras.preprocessing.sequence import pad_sequences     # pad_sequences is used to ensure that all sequences in a list have the same length.
from tensorflow.keras.models import Sequential                        # The deep learning model is created layer by layer so we are using sequential
from tensorflow.keras.layers import Dense,Embedding,LSTM   # Dense Layer is a simple layer of neurons in which each neurons recives input from all the neurons of previous layer,  Embedding is a technique which converts word into vector
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix
from sklearn.metrics import roc_curve,roc_auc_score

"""**Loading the dataset**"""

fake=pd.read_csv('/content/drive/MyDrive/batch 24 from shan sir/capstrone project fake and real news/Fake and real news/Fake.csv')
real=pd.read_csv('/content/drive/MyDrive/batch 24 from shan sir/capstrone project fake and real news/Fake and real news/True.csv')

fake.shape

real.shape

fake.head()

real.head(10)

fake.columns

fake.subject.value_counts()

plt.figure(figsize=(10,6))
sns.countplot(fake.subject)
plt.show()

"""# word cloud"""

type(fake.text)

# now will mix all the text data together
text=' '.join(fake['text'].tolist())             # the fake.text was in series we are going to convert into list and then we are joining in to a single sentence

# printing the wordcloud of fake text data
wordcloud=WordCloud().generate(text)
plt.imshow(wordcloud)

# will plot the same in clear format by increasing the size of the image
wordcloud=WordCloud(width=1920,height=1000).generate(text)          # we are using wordcloud to visualize more frequent word present in the sentence
fig=plt.figure(figsize=(10,10))
plt.imshow(wordcloud)
plt.axis('off')             # to swith off the axis
plt.show()

"""Will plot the word plot for real news"""

text=' '.join(real['text'].tolist())

# will plot the same in clear format by increasing the size of the image
wordcloud=WordCloud(width=1920,height=1000).generate(text)          # we are using wordcloud to visualize more frequent word present in the sentence
fig=plt.figure(figsize=(10,10))
plt.imshow(wordcloud)
plt.axis('off')             # to swith off the axis
plt.show()

"""you can see both fake and real wordcloud are same but in real wordcloud you can see that 'white house' and 'washington reuters' are repeated most of the time in real news

If it is real news then their will be reference to the publications

Difference in Text

Real news seems to have source of publication which is not present in fake news set
Looking at the Data:



*   Most of text contains reuters information such as **washington (Reuters)**
*   Some text are tweets from Twitter
*   Few text do not contain any publication info

# Cleaning Data

## Removing Reuters or Twitter Tweet Information from the text

  *  Text can be splitted only once at "**-**" which is always present after mentioning source of publication, this gives us publication part and text part
  *  If we do not get text part, this means publication details was'nt given for the record
  *  The Twitter tweets always have same source, a long text of max 120 characters
"""

real.text[0]

# Now will create list of indexes which donot have publication information (performing exception handling)

unknown_publishers=[]
for index,row in enumerate(real.text.values):
  try:
    record=row.split('-',maxsplit=1)         # this code is a critical statement so i dont want to stop the execution if i get the error so i am using try
    assert(len(record[0])<120)               # we declares a condition to be true using assert statement prior to running the module
  except:
    unknown_publishers.append(index)

# For example how exception handling works
a=5
b=0
try:
  print(a/b)
except:
  print('you cannot divide a number by 0')

len(unknown_publishers)

real.iloc[unknown_publishers].text

# Checking for missing values
real.text[real.text==' ']

real.iloc[8970]

# Droping the missing values
real= real.drop(8970,axis=0)

# Spliting the publisher info and text if publishers info is not exist we are filling with unknown publisher
publisher = []
tmp_text = []

for index,row in enumerate(real.text.values):
  if index in unknown_publishers:
    tmp_text.append(row)
    publisher.append('Unknown')

  else:
    record=row.split('-',maxsplit=1)
    publisher.append(record[0].strip())
    tmp_text.append(record[1].strip())

real['publisher']=publisher
real['text']=tmp_text

np.array(publisher).shape

# will check if their is any empty text present in the real data
[index  for index,text in enumerate(real.text.tolist()) if str(text).strip()=='']

# will check if their is any empty text present in the fake data
empty_fake_index=[index  for index,text in enumerate(fake.text.tolist()) if str(text).strip()=='']

len(empty_fake_index)

fake.iloc[empty_fake_index]

# we are adding title and text to gether to the text column
real['text']=real['title'] + ' '+ real['text']
fake['text']=fake['title']+' '+fake['text']

"""Preprocessing Text"""

real['class']= 1
fake['class']=0

real.columns

real=real[['text','class']]
fake=fake[['text','class']]

data=real.append(fake,ignore_index=True)

data.sample(5)

"""Text Cleaning"""

## Now will remove all the special character in the data for example
re.sub('[^A-Za-z0-9 ]', '', 'this ,. @ is # gre@t')      # by using regression expression substituting (which are all not in A-Za-z0-9)

data.text.head()

message=data.text.to_list()
message[0]

len(message)

# Dataset Preprocessing and applying stemming

from nltk.stem.porter import PorterStemmer
from nltk.corpus import stopwords
nltk.download('stopwords')
ps = PorterStemmer()
stop_words_lis= stopwords.words('english')
stop_words_lis.remove('not')
corpus = []
for i in range(0,len(message)):
  review = re.sub('[^a-zA-Z]',' ',message[i])
  review = review.lower()
  review = review.split()
  review = [ps.stem(word) for word in review if not word in stop_words_lis]
  reveiw = ' '.join(review)
  corpus.append(reveiw)

corpus[0]

data.head()

"""Applying Countvectorizer

Creating the Bag of Words Model
"""

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,ngram_range=(1,3))
X = cv.fit_transform(corpus).toarray()

y=data['class']

## Divide the dataset into Train and Test
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.33,random_state=0)

count_df = pd.DataFrame(X_train,columns=cv.get_feature_names())

count_df.head()

"""MultinomialNB Algorithm"""

from sklearn.naive_bayes import MultinomialNB
classifier=MultinomialNB()

from sklearn import metrics
import numpy as np
import itertools

classifier.fit(X_train,y_train)
pred = classifier.predict(X_test)
score = metrics.accuracy_score(y_test,pred)
print('accuracy =',score)

confusion_matrix(y_test,pred)

cm = confusion_matrix(y_test,pred)
cm = pd .DataFrame(cm , index = ['Fake','Original'] , columns = ['Fake','Original'])
plt.figure(figsize = (7,7))
sns.heatmap(cm,cmap= "Oranges", linecolor = 'black' , linewidth = 1 , annot = True, fmt='' , xticklabels = ['Fake','Original'] , yticklabels = ['Fake','Original'])
plt.xlabel("Predicted")
plt.ylabel("Actual")

"""Multinomial Classifier with Hyperparameter


"""

classifier=MultinomialNB(alpha=0.1)

previous_score=0
for alpha in np.arange(0,1,0.1):
  sub_classifier=MultinomialNB(alpha=alpha)
  sub_classifier.fit(X_train,y_train)
  y_pred=sub_classifier.predict(X_test)
  score = metrics.accuracy_score(y_test,y_pred)
  if score>previous_score:
    print(f'alpha : {alpha} score : {score}')

"""# TF-IDF Vectorizer"""

from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_v=TfidfVectorizer(max_features=5000,ngram_range=(1,3))
X=tfidf_v.fit_transform(corpus).toarray()

X.shape

y=data['class']

# Dividing the dataset into Train and Teset
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test =train_test_split(X,y,test_size=0.3,random_state=0)

tfidf_v.get_feature_names()[:10]

# To see how the vector is formed by using TFIDF
count_df = pd.DataFrame(X_train,columns=tfidf_v.get_feature_names())

count_df.head()

"""MultinomialNB Algorithm"""

classifier=MultinomialNB()

classifier.fit(X_train,y_train)
pred = classifier.predict(X_test)
score = metrics.accuracy_score(y_test,pred)
print('accuracy =',score)

confusion_matrix(y_test,pred)

cm = confusion_matrix(y_test,pred)
cm = pd .DataFrame(cm , index = ['Fake','Original'] , columns = ['Fake','Original'])
plt.figure(figsize = (7,7))
sns.heatmap(cm,cmap= "Oranges", linecolor = 'black' , linewidth = 1 , annot = True, fmt='' , xticklabels = ['Fake','Original'] , yticklabels = ['Fake','Original'])
plt.xlabel("Predicted")
plt.ylabel("Actual")

"""Multinomial Classifier with Hyperparameter


"""

classifier=MultinomialNB(alpha=0.1)

previous_score=0
for alpha in np.arange(0,1,0.1):
  sub_classifier=MultinomialNB(alpha=alpha)
  sub_classifier.fit(X_train,y_train)
  y_pred=sub_classifier.predict(X_test)
  score = metrics.accuracy_score(y_test,y_pred)
  if score>previous_score:
    print(f'alpha : {alpha} score : {score}')

"""# Now we want to convert this text data to vectorization so we will be using Word2vec

![image.png](attachment:image.png)

# Vectorization -- Word2Vec

## Word2Vec is one of the most popular technique to learn word embeddings using shallow neural network. It was developed by Tomas Mikolov in 2013 at Google.

## word embedding is the most popular representation of document vocabulary. It is capable of capturing context of word in a document, semantic and syntatic similarity, relation with other words, etc
"""

import gensim

y=data['class'].values

# Now will convert the text in list of list
# X=[i.split() for i in data['text'].tolist()]

x=[i.split()  for i in corpus]

print(x[0])

# print(X[0])

len(x[0])

DIM=100
w2v_model = gensim.models.Word2Vec(sentences=x,size=DIM,window=11)    # here we are going to make 11 seperate window(group) and if their is only 1 data at the last we must convert it in to vector

# Now will check the most similar word in our model  this is with the help of gensim
w2v_model.wv.most_similar('india')

tokenizer = Tokenizer()
tokenizer.fit_on_texts(x)

X=tokenizer.texts_to_sequences(x)

#tokenizer.word_index

plt.hist([len(i) for i in x],bins=800)
 plt.show()

"""Most of the list contains between 300 to 500 words"""

# now will will print the index which have more than 600 words in the list
nos=np.array([len(i) for i in x])
len(nos[nos>600])                    # we have 1497 sentences which have more than 600 words

"""### Now will make some changes which ever sentences having greater than 600 words will be limited to 600 words and which ever sentences is less than 600 words will do padding and fill 0 at the initial stage and make the size =600"""

maxlen=600
X=pad_sequences(X,maxlen=maxlen)

# Now will check the size of the sentences randomly
X[1021].size

vocab_size = len(tokenizer.word_index) + 1
vocab=tokenizer.word_index

def get_weight_matrix(model):
  weight_matrix=np.zeros((vocab_size,DIM))

  for word,i in vocab.items():
    weight_matrix[i] = model.wv[word]

  return weight_matrix

embedding_vectors = get_weight_matrix(w2v_model)

embedding_vectors.shape

model = Sequential()
model.add(Embedding(vocab_size,output_dim=DIM,weights=[embedding_vectors],input_length=maxlen,trainable=False))
model.add(LSTM(units=128))
model.add(Dense(1,activation='sigmoid'))
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['acc'])

model.summary()

# Now will do train test split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

print(X_train[0:5])
print(y_train[0:5])

model.fit(X_train,y_train,validation_split=0.3,epochs=6)

y_pred=(model.predict(X_test) >=0.5).astype(int)

accuracy=accuracy_score(y_test,y_pred)
accuracy

print(classification_report(y_test,y_pred))

confusion_matrix(y_test,y_pred)

cm = confusion_matrix(y_test,y_pred)
cm = pd .DataFrame(cm , index = ['Fake','Original'] , columns = ['Fake','Original'])

plt.figure(figsize = (7,7))
sns.heatmap(cm,cmap= "Oranges", linecolor = 'black' , linewidth = 1 , annot = True, fmt='' , xticklabels = ['Fake','Original'] , yticklabels = ['Fake','Original'])
plt.xlabel("Predicted")
plt.ylabel("Actual")

def plot_roc_curve(fpr,tpr):
    plt.figure(figsize = (20,5))
    plt.plot(fpr,tpr, color = 'green')
    plt.axis([0,1,0,1])
    plt.xlabel('False Positive Rate')
    plt.ylabel('True Positive Rate')
    plt.show()

fpr , tpr , thresholds = roc_curve (y_test , y_pred)
plot_roc_curve(fpr,tpr)

# Now will write a function that takes a input news and predict if the news is fake or original

def predicting_news(a):
    new_data=tokenizer.texts_to_sequences(a)
    new_data=pad_sequences(new_data,maxlen=maxlen)
    output=(model.predict(new_data) >=0.5).astype(int)
    if output >0.5:
        print('The Given News is Original')
    else:
        print('The Given News is Fake')

a=["Russia Ukraine War Crisis Live Updates, July 02, 2022: As reported by Reuters, the Ambassador to Russia of the pro-Moscow self-styled Luhansk People's Republic, Rodion Miroshnik, told Russian television Lysychansk has been brought under control."]
predicting_news(a)

# https://www.statista.com/topics/5846/fake-news-in-india/#dossierKeyfigures  for fake news artical
a=['In a post-truth era, the contagion of fake news has gripped the world in equal parts. Right from the United states of America, to emerging economies like India, Brazil and others, no one seems to be spared. Deeply interlinked with technological developments, “disinformation” and “misinformation” have become pervasive in our news bubbles. As the world’s largest democracy with the second largest population, the issue of fake news poses a unique threat in India. Not only do the low literacy rates make it hard to implement the true spirit of democratic decision-making, but add to that an explosion of fake news and divisive propaganda, and there looms a real threat to the country’s democratic fabric itself.']
predicting_news(a)

a=["India logged 16,103 new coronavirus infections taking the total tally of COVID-19 cases to 4,35,02,429, while the active cases increased to 1,11,711, according to the Union Health Ministry data updated on Sunday"]
predicting_news(a)

# https://www.statista.com/statistics/1027070/india-responsibility-to-solve-misinformation-problem/
a=['About 51 percent of the survey respondents agreed that they are concerned when facts were spun or twisted to push a particular agenda through fake news media. Fake news and disinformation through social media has been a pressing issue in many countries across the world today. In India as well, this concern was reflected in good measure with a majority of the respondents stating they were worried about fake news being a problem due to various reasons.']
predicting_news(a)

